apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-3d
  labels:
    app: kubernetes-3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-3d
  template:
    metadata:
      labels:
        app: kubernetes-3d
    spec:
      containers:
      - name: kubernetes-3d
        image: reneschoonrok/kubernetes-3d-visualizer:latest
        env:
        - name: TOKEN
          value: "exposed"